"""
BRD-AI: SKILL脚本生成器 (Module 5)
将约束规则转换为Cadence Allegro可执行的SKILL脚本
"""
from jinja2 import Template
from typing import Dict, Any, List
import os


SKILL_TEMPLATE = """\
; ============================================================
; Auto-generated Cadence Allegro Constraint Script
; Generated by BRD-AI System
; {{ timestamp }}
; Board: {{ board_name }}
; Capability: {{ capability_level }}
; ============================================================
;
; 使用方法:
;   1. 打开 Allegro PCB Editor
;   2. 在Command窗口输入: skill load "auto_constraint.il"
;   3. 或: File -> Script -> Replay -> 选择此文件
;
; ============================================================

(defun BRD_AI_CreateAllConstraints ()
  (let (result)
    (printf "\\n========================================\\n")
    (printf "BRD-AI: 开始创建 Constraint...\\n")
    (printf "========================================\\n\\n")

    ; ---- 进入 Constraint Manager ----
    (axlCNSEnter)

{% for nc in net_classes %}
    ; ---- Net Class: {{ nc.name }} ({{ nc.count }} nets) ----
    (printf "Creating Net Class: {{ nc.name }}\\n")
    (axlCNSAddNetClass "{{ nc.name }}"
      '(
{% for net in nc.nets %}
        "{{ net }}"
{% endfor %}
      ))
    (printf "  -> {{ nc.name }}: {{ nc.count }} nets added\\n")
{% endfor %}

    (printf "\\nNet Classes created: {{ net_classes|length }}\\n\\n")

{% for phys in physical_constraints %}
    ; ---- Physical Constraint: {{ phys.name }} ----
    (printf "Setting Physical: {{ phys.name }}\\n")
    (axlCNSAddPhysicalConstraint "{{ phys.name }}"
      '("width" "neck_width" "max_width")
      '({{ phys.width_min }} {{ phys.width_min }} {{ phys.width_max }})
    )
    (axlCNSSetPreferredWidth "{{ phys.name }}" {{ phys.width_preferred }})
    (axlCNSSetNetClassConstraint "{{ phys.name }}" "{{ phys.net_class }}")
{% endfor %}

    (printf "\\nPhysical constraints set: {{ physical_constraints|length }}\\n\\n")

{% for spc in spacing_constraints %}
    ; ---- Spacing Constraint: {{ spc.name }} ----
    (printf "Setting Spacing: {{ spc.name }}\\n")
    (axlCNSAddSpacingConstraint "{{ spc.name }}"
      '("line_to_line" "line_to_pin" "line_to_via")
      '({{ spc.line_to_line }} {{ spc.line_to_pin }} {{ spc.line_to_via }})
    )
    (axlCNSSetNetClassConstraint "{{ spc.name }}" "{{ spc.net_class }}")
{% endfor %}

    (printf "\\nSpacing constraints set: {{ spacing_constraints|length }}\\n\\n")

{% for via in via_constraints %}
    ; ---- Via Constraint: {{ via.name }} ----
    (printf "Setting Via: {{ via.name }}\\n")
    (axlCNSAddViaConstraint "{{ via.name }}"
      '("drill" "pad")
      '({{ via.drill }} {{ via.pad }})
    )
    (axlCNSSetNetClassConstraint "{{ via.name }}" "{{ via.net_class }}")
{% endfor %}

    (printf "\\nVia constraints set: {{ via_constraints|length }}\\n\\n")

{% for dp in diff_pairs %}
    ; ---- Diff Pair: {{ dp.name }} ----
    (printf "Creating Diff Pair: {{ dp.name }}\\n")
    (axlCNSAddDiffPair "{{ dp.name }}"
      "{{ dp.p_net }}" "{{ dp.n_net }}"
    )
{% endfor %}

    (printf "\\nDiff Pairs created: {{ diff_pairs|length }}\\n\\n")

{% for elec in electrical_constraints %}
{% if elec.is_diff_pair %}
    ; ---- Electrical Constraint: {{ elec.name }} ----
    (printf "Setting Electrical: {{ elec.name }}\\n")
    (axlCNSAddElectricalConstraint "{{ elec.name }}"
      '("diff_pair_impedance" "diff_pair_line_width" "diff_pair_gap")
      '({{ elec.impedance_target }} {{ elec.min_line_width }} {{ elec.min_gap }})
    )
    (axlCNSSetDiffPairImpedanceTolerance "{{ elec.name }}" {{ elec.impedance_tolerance }})
    (axlCNSSetNetClassConstraint "{{ elec.name }}" "{{ elec.net_class }}")
{% endif %}
{% endfor %}

    (printf "\\nElectrical constraints set: {{ electrical_constraints|length }}\\n\\n")

    ; ---- 退出 Constraint Manager ----
    (axlCNSExit)

    (printf "\\n========================================\\n")
    (printf "BRD-AI: Constraint 创建完成!\\n")
    (printf "========================================\\n\\n")
    t
  )
)

; ---- 执行 ----
(BRD_AI_CreateAllConstraints)
"""


def generate_skill_script(
    constraints: dict,
    signal_classification: dict,
    board_name: str = "Untitled",
    capability_level: str = "standard",
    output_path: str = None,
) -> str:
    from datetime import datetime
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    net_classes = signal_classification.get("net_classes", {})
    net_class_list = []
    for cls_name, cls_info in net_classes.items():
        net_class_list.append({
            "name": cls_name,
            "nets": cls_info.get("nets", []),
            "count": cls_info.get("count", len(cls_info.get("nets", []))),
        })

    diff_pairs = signal_classification.get("diff_pairs", [])
    diff_pair_list = []
    for i, dp in enumerate(diff_pairs):
        diff_pair_list.append({
            "name": f"DP_{i+1}",
            "p_net": dp.get("p_net", ""),
            "n_net": dp.get("n_net", ""),
        })

    template = Template(SKILL_TEMPLATE)
    skill_content = template.render(
        timestamp=timestamp,
        board_name=board_name,
        capability_level=capability_level,
        net_classes=net_class_list,
        physical_constraints=constraints.get("physical_constraints", []),
        spacing_constraints=constraints.get("spacing_constraints", []),
        via_constraints=constraints.get("via_constraints", []),
        diff_pairs=diff_pair_list,
        electrical_constraints=constraints.get("electrical_constraints", []),
    )

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(skill_content)

    return skill_content